### ISSUE TITLE
libqcustomplot2.0 dependency

### ISSUE THREAD

**Issue by rtang-sidney** [ILLGrenoble/taspaths#1]
Hi Tobi,

I had an issue installing the software because of the dependency on libqcustomplot2.0. I have Ubuntu Noble 24.04, where libqcustomplot2.1 is installed. However, the installation process did not recognise the 2.1 version even after reinstallation:

**taspaths depends on libqcustomplot2.0 (>= 2.0.0); however:
  Package libqcustomplot2.0 is not installed.**

I tried to install the version 2.0 but got the error message:

**Package libqcustomplot2.0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libqcustomplot2.1-qt6 libqcustomplot2.1
E: Package 'libqcustomplot2.0' has no installation candidate**

When I google "libqcustomplot2.0 Noble 24.04", I get only results about the version 2.1. Do you have experience with such a compatibility issue? Do I have to downgrade my Ubuntu version to 22.04?

Many thanks

Ran

**Comment by tweber-ill** [comment]
Thanks Ran for the report, the build script has now been updated for 24.04:
https://github.com/ILLGrenoble/taspaths/commit/14bf2a409f0335f6a8f16c09cba1ea26d9963afb
